"""Add XP logs relationship

Revision ID: 5b6e0549e68b
Revises: 0176b72af303
Create Date: 2026-02-02 08:33:27.699730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6e0549e68b'
down_revision = '0176b72af303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('habit_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('icon')
        batch_op.drop_column('category')
        batch_op.drop_column('color')
        batch_op.drop_column('frequency')

    with op.batch_alter_table('habit_completion', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_habit_completion_per_day'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_completion', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_habit_completion_per_day'), ['habit_id', 'date'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('habit_user_id_fkey'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
