"""Add Habit and HabitCompletion tables

Revision ID: 89a1c65fab6a
Revises: 465fe3b94217
Create Date: 2026-02-01 07:10:21.956849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a1c65fab6a'
down_revision = '465fe3b94217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)

    with op.batch_alter_table('habit_completion', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_habit_per_day'), type_='unique')
        batch_op.create_unique_constraint('unique_habit_completion_per_day', ['habit_id', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_completion', schema=None) as batch_op:
        batch_op.drop_constraint('unique_habit_completion_per_day', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_habit_per_day'), ['habit_id', 'date'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
