# app/main/quotes.py
import random

quotes = [
    "🌟 Every small step counts!",
    "💪 You are stronger than yesterday.",
    "🔥 Keep the streak alive!",
    "✨ Consistency is key.",
    "🚀 Today is another chance to improve.",
    "🏆 Small wins lead to big victories.",
    "🌱 Growth comes from daily habits.",
    "💎 Your effort compounds over time.",
    "⚡ Push yourself, stay consistent.",
    "🌈 Every habit is a new rainbow.",
    "🎯 Focus on progress, not perfection.",
    "🕒 One day at a time, keep going.",
    "🌻 Bloom where you are planted.",
    "🏔️ Climb every mountain, start small.",
    "💡 Habits shape your future.",
    "🎵 Make your actions sing.",
    "🔥 Light the fire within.",
    "📈 Daily progress > occasional effort.",
    "🌊 Small ripples create big waves.",
    "🌟 Shine with every habit you do.",
    "🏃‍♂️ Movement today leads to strength tomorrow.",
    "🍀 Luck favors the consistent.",
    "🌞 Rise, shine, and habit on!",
    "🎯 Every goal begins with a habit.",
    "🌱 Plant a habit, reap success.",
    "💫 Tiny actions, huge transformations.",
    "🛤️ The path is made by walking.",
    "🏹 Aim high, act daily.",
    "🎵 Let your routine be your rhythm.",
    "🌻 Consistency is your sunshine.",
    "🔥 Stay hot, keep going.",
    "💪 Your streak is your superpower.",
    "🌈 Color your life with good habits.",
    "🚴‍♀️ Progress is a journey, not a sprint.",
    "🏆 Every habit is a trophy earned.",
    "🌟 Stars shine after darkness; keep pushing.",
    "💡 Ideas need actions to grow.",
    "🎯 Small habits, big targets.",
    "🌊 Drop by drop, the ocean is formed.",
    "🍀 Good habits bring good fortune.",
    "🔥 Keep your inner fire alive.",
    "🌞 Today is your stepping stone.",
    "🏔️ Small climbs lead to great peaks.",
    "💎 Polish your habits, shine your life.",
    "🕒 One habit a day, a better you.",
    "🌱 Nurture your habits, grow your future.",
    "🎵 Make every day count.",
    "⚡ Energy + Consistency = Results.",
    "🏹 Focused effort always wins.",
    "🌈 Habits make life colorful.",
    "💪 Strength lies in small daily actions.",
]

def get_random_quote():
    """Return a random quote from the list."""
    return random.choice(quotes)

